### Variables
@baseUrl = http://localhost:8081
@apiKey = {{createAccount.response.body.api_key}}

### Create a new account
# @name createAccount
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name": "Mesaque Botelho Junior",
    "email": "mesaque@test.com"
}

### Get the account
GET {{baseUrl}}/accounts
X-API-Key: {{apiKey}}

### Create a new invoice
# @name createInvoice
POST {{baseUrl}}/invoice
Content-Type: application/json
X-API-Key: {{apiKey}}

{
    "amount": 100.50,
    "description": "Test invoice",
    "payment_type": "credit_card",
    "card_number": "4111111111111111",
    "cvv": "123",
    "expiry_month": 12,
    "expiry_year": 2025,
    "cardholder_name": "Mesaque Botelho Junior"
}

### Get the invoice
GET {{baseUrl}}/invoice
X-API-Key: {{apiKey}}
### Get the invoice by ID
@invoiceId = {{createInvoice.response.body.id}}
GET {{baseUrl}}/invoice/{{invoiceId}}
X-API-Key: {{apiKey}}

### Create new invoce with value > 10000
POST {{baseUrl}}/invoice
Content-Type: application/json
X-API-Key: {{apiKey}}

{
    "amount": 15000.50,
    "description": "Test invoice",
    "payment_type": "credit_card",
    "card_number": "4111111111111111",
    "cvv": "123",
    "expiry_month": 12,
    "expiry_year": 2025,
    "cardholder_name": "Mesaque Botelho Junior"
}
